images:
- gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA

steps:
- name: 3778/covid-19
  args: ['pytest', '--doctest-modules', '--verbose', 'covid19/']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
  timeout: 240s
