name: Build and Deploy to GKE

on:
  push:
    branches:
      - git-actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY}}
          heroku_app_name: hospital-queue-model #Must be unique in Heroku
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          #buildpack: "SOME BUILDPACK" #OPTIONAL
          branch: develop #OPTIONAL and DEFAULT - 'HEAD' (a.k.a your current branch)
          dontuseforce: false #OPTIONAL and DEFAULT - false
          usedocker: true #OPTIONAL and DEFAULT - false
